services:
    - type: web
      name: imageboard
      env: node
      plan: free
      startCommand: npm run start
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: socialnetwork
                property: connectionString

databases:
    - name: socialnetwork
      plan: free
