services:
    - type: web
      name: imageboard
      env: node
      plan: free
      startCommand: node server.js
      buildCommand: npm install
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: socialnetwork
                property: connectionString

databases:
    - name: socialnetwork
      plan: free

envVarGroups:
    - name: imageboard
