services:
    - type: web
      name: great-image-bazaar
      env: node
      plan: free
      region: frankfurt
      startCommand: node server.js
      buildCommand: npm install
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: socialnetwork_gx5o
                property: connectionString

databases:
    - name: socialnetwork_gx5o
      plan: free

